version: '3'
services:
  initializer:
      image: alpine
      container_name: solr-initializer
      restart: "no"
      entrypoint: |
        /bin/sh -c "chown 8983:8983 /solr"
      volumes:
        - ./data/solr:/solr

  fastapi:
    container_name: fastapi
    build: ./src/api
    #command: bash -c "pip install -e . && cd api && source /home/setup/delete_cores_curl.sh && uvicorn main:app --host 0.0.0.0"
    command: bash -c "pip install -e . && cd api && sleep 15 && source /home/setup/curl/startup_cores.sh && uvicorn main:app --reload --host 0.0.0.0"
    #command: bash -c "pip install -e . && cd api && uvicorn main:app --host 0.0.0.0"
    volumes:
      - ./src/:/app/
      - ./solr-setup/curl:/home/setup/curl
      - ./documents:/home/documents
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      initializer:
        condition: service_completed_successfully

  solr:
    container_name: solr
    image: solr:9.1.1
    ports:
     - "8983:8983"
    command: bash -c "source /home/setup/curl/prepare_dir.sh"
    depends_on:
      - fastapi
    volumes:
      - ./data/solr:/var/solr
      - ./solr-setup/curl:/home/setup/curl
      - ./documents:/home/documents
      #- ./embeddings:/home/embeddings
    environment:
      - SOLR_OPTS=-Dsolr.jetty.request.header.size=65535
    restart: always

    
  #nlp:
  #  container_name: nlp
  #  build: ./src/nlp
  #  command: bash -c "pip install -e . && python -m spacy download en_core_web_sm && python -m spacy download en_core_web_md && python -m spacy download en_core_web_lg && python -m spacy download en_core_web_trf && python -m spacy download en_core_web_trf"
  #  volumes:
  #    - ./:/app/
  #  depends_on:
  #    - fastapi
    

volumes:
  data:
