version: '3'
services:
  initializer:
      image: alpine
      container_name: solr-initializer
      restart: "no"
      entrypoint: |
        /bin/sh -c "chown 8983:8983 /solr"
      volumes:
        - ./data/solr:/solr

  solr:
    container_name: solr
    image: solr:9.1.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/cores?action=STATUS"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      initializer:
        condition: service_completed_successfully
    ports:
     - "8983:8983"                      
    volumes:
      - ./solr-data:/var/solr
      - ./solr-setup:/home/setup
      - ./embeddings:/home/embeddings
    environment:
      - SOLR_OPTS=-Dsolr.jetty.request.header.size=65535

volumes:
  data: